---
- name: Ensure build prerequisites are installed
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - binutils
    - make
    - gcc
    - fakeroot
    - expac
    - yajl
    - git
    - cower

- name: "Create {{ aur_build_user}} user"
  user:
    name: "{{ aur_build_user }}"
    append: true
    groups: wheel
    state: present

- name: Check if pacaur is installed
  command: 'pacman -Q pacaur'
  failed_when: false
  changed_when: aur_pacaur_check.rc != 0
  register: aur_pacaur_check

- name: Download pacaur
  shell: "cower -dqf --target=$(eval echo ~{{ aur_build_user }}/) pacaur"
  become: true
  become_user: "{{ aur_build_user }}"
  when: aur_pacaur_check.rc != 0

- name: Install pacaur
  command: "makepkg PKGBUILD --install --needed --noconfirm"
  args:
    chdir: "~{{ aur_build_user }}/pacaur/"
  become: true
  become_user: "{{ aur_build_user }}"
  notify: Cleanup pacaur build directory
  when: aur_pacaur_check.rc != 0
